export const COMPANY_NAME = "KYRIE PETRAKIS"
export const LOGO1 = require('../assets/logo-1.png');
export const LOGO2 = require('../assets/logo-2.png');
export const HERO_BG_IMG = require('../assets/s2.webp');
export const ABOUT_BG = require('../assets/pexels-sora-shimazaki-5668473.jpg');
export const TESTIMONIALS_BG_IMG = require('../assets/design-img.png');
export const INCOME_TAX = require('../assets/taxes_4749988.png');
export const GST = require('../assets/tax_9323080.png');
export const CRIMINAL = require('../assets/man_4406773.png');
export const CIVIL = require('../assets/auction_783196.png');
export const OTHHERS = require('../assets/justice-scale_12088194.png');
export const WHYUS_BG = require('../assets/pexels-sora-shimazaki-5668772.jpg');